export const GET_CINEMAS = 'GET_CINEMAS';
export const GET_CINEMA_MOVIES = 'GET_CINEMA_MOVIES';
export const GET_UPCOMING_MOVIES = 'GET_UPCOMING_MOVIES';
export const GET_MOVIE_DETAILS_BY_ID = 'GET_MOVIE_DETAILS_BY_ID';
